language: cpp
sudo: false

compiler:
- clang

branches:
  except:
  - /^.*-dev$/

env:
  global:
  - MAKEFLAGS="-j2"

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libssl1.0-dev
    - libboost1.61-dev
    - libboost-system1.61-dev
    - libboost-iostreams1.61-dev

before_script:
- cmake .

script:
- make -j2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
