language: cpp
sudo: false

compiler:
- clang

branches:
  except:
  - /^.*-dev$/

env:
  global:
  - MAKEFLAGS="-j2"

addons:
  apt:
    packages:
    - libssl-dev
    - libboost-dev
    - libboost-system-dev

before_script:
- cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON

script:
- make -j2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
