language: cpp
sudo: false

compiler:
- clang

branches:
  except:
  - /^.*-dev$/
  - dev

env:
  global:
  - MAKEFLAGS="-j2"

addons:
  apt:
    packages:
    - libssl-dev
    - libboost-dev
    - libboost-system-dev
    - libboost-iostreams-dev

before_script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON

script:
- make -j2
- make test

# TODO:
# Auto-publish documentation.
